// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhsXGwaVSor0v5McPSXK0V7QhhUQUEUeE',
    appId: '1:1030988524707:web:909602cf7bd0ed789d2316',
    messagingSenderId: '1030988524707',
    projectId: 'happy-birthday-mama-b05ec',
    authDomain: 'happy-birthday-mama-b05ec.firebaseapp.com',
    storageBucket: 'happy-birthday-mama-b05ec.appspot.com',
    measurementId: 'G-ZXQZCKX8YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmRBEfL8_Uvg9uiE52IQkvHN3RbisbkP0',
    appId: '1:1030988524707:android:eca6636de34aceca9d2316',
    messagingSenderId: '1030988524707',
    projectId: 'happy-birthday-mama-b05ec',
    storageBucket: 'happy-birthday-mama-b05ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-VxvUpp5IDkYwZHmwsZYwsdx4_eAiDcQ',
    appId: '1:1030988524707:ios:803b10b716c481d79d2316',
    messagingSenderId: '1030988524707',
    projectId: 'happy-birthday-mama-b05ec',
    storageBucket: 'happy-birthday-mama-b05ec.appspot.com',
    iosBundleId: 'com.example.happyBirthdayMom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-VxvUpp5IDkYwZHmwsZYwsdx4_eAiDcQ',
    appId: '1:1030988524707:ios:abcb1d5f02f267679d2316',
    messagingSenderId: '1030988524707',
    projectId: 'happy-birthday-mama-b05ec',
    storageBucket: 'happy-birthday-mama-b05ec.appspot.com',
    iosBundleId: 'com.example.happyBirthdayMom.RunnerTests',
  );
}
